# Generated by Django 5.1.1 on 2024-10-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wardrobe',
            old_name='material',
            new_name='formality',
        ),
    ]
